version: 2.1

orbs:
  gh: circleci/github-cli@2.0

#####################################################
# Parameters
#####################################################
parameters:
  sources-changed:
    type: boolean
    default: false

#####################################################
# Workflows
#####################################################
jobs:
  # create-a-pr:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - gh/setup
  #     - run:
  #         command: |
  #           gh pr create --title "Bugfix from $CIRCLE_BRANCH"
  #         name: Create Pull Request
  #     - gh/clone
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - gh/setup:
          token: GITHUB_TOKEN
      - run: git checkout -b xx
      - run: cp -f test.txt test-copy.txt
      - run: git commit -am "make a copy of test.txt"
      - run: git push origin xx
      - run:
          command: |
            gh pr create --title "Bugfix from $CIRCLE_BRANCH"
          name: Create Pull Request

  echo-token:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo $GITHUB_TOKEN

workflows:
  version: 2
  test-token:
    jobs:
      - echo-token:
        context:
          - GITHUB_TOKEN
  my-workflow:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ true, << pipeline.parameters.sources-changed >> ]
    jobs:
      - my-job:
        context:
          - GITHUB_TOKEN